name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # nebo master, záleží na vaší větvi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        mkdir -p out
        cp -r public/* out/
        cd out
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force "https://${{ github.token }}@github.com/${{ github.repository }}.git" main:gh-pages
